# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd2cf5fd967f869280001cf7958277944c283b5eab277d132ac152c2f8f41188bc7ee7aa608fb7b71dbc9189dcc9eb93507fd1a9e7af35aac7734f3cb1ab1338

test:
  secret_key_base: fb3476a1f1b8294ea40a3a79a0d0a491e5fa5647262c412194811df9aa2789a4053ad8337cc034a33ec57d15a95ca586f3e24648a138999f45188dec715f1c3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
